"""
================================================================================
VERIFICATION SCRIPT: PHASE 5C
================================================================================

OFFICIAL TARGET:
  File: soroban_project/src/train/project_3_killer_test_adversarial_carry_chain.py

PURPOSE:
  Verify the arithmetic ground-truth semantics of the adversarial patterns
  generated by Project 3 killer-test source.

THIS SCRIPT VERIFIES:
  1. The generated patterns are arithmetically coherent
  2. Local sum sequences match independent carry-propagation computation
  3. The visible pattern descriptions align with actual sequence structure
  4. Basic adversarial intentions are reflected in the generated operands

THIS SCRIPT DOES NOT VERIFY:
  - Model predictions
  - Metric correctness
  - Official reproduction
  - Broader claims about model reasoning

IMPORTANT PRINCIPLE:
  Step 5C asks:
    "Are the generated adversarial patterns and their arithmetic structure correct?"
  It does NOT ask:
    "How well does the model perform on them?"

================================================================================
"""

import importlib.util
import sys
from pathlib import Path

import numpy as np


# ============================================================================
# PATHS
# ============================================================================
ROOT = Path(__file__).resolve().parents[2]
TARGET_FILE = ROOT / "src" / "train" / "project_3_killer_test_adversarial_carry_chain.py"


# ============================================================================
# HELPERS
# ============================================================================

def print_header(title):
    print("\n" + "=" * 80)
    print(title)
    print("=" * 80)


def fail(msg):
    print(f"\nERROR: {msg}")
    sys.exit(1)


def load_target_module(filepath):
    spec = importlib.util.spec_from_file_location(
        "project_3_killer_test_adversarial_carry_chain",
        str(filepath)
    )
    if spec is None or spec.loader is None:
        fail(f"Could not create import spec for: {filepath}")

    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def reference_local_sum_sequence(a_seq, b_seq):
    """
    Independent carry-propagating local-sum reference.

    Returns local sums in [0..19], not final decimal digits.
    """
    if len(a_seq) != len(b_seq):
        raise ValueError("a_seq and b_seq must have equal length")

    out = []
    carry = 0
    for a, b in zip(a_seq, b_seq):
        s = int(a) + int(b) + carry
        out.append(s)
        carry = 1 if s >= 10 else 0
    return out


def describe_pattern_structure(name, a_arr, b_arr, desc):
    print(f"\nPattern: {name}")
    print(f"Description: {desc}")
    print(f"a shape: {a_arr.shape}")
    print(f"b shape: {b_arr.shape}")
    print(f"First sample a: {a_arr[0].tolist()}")
    print(f"First sample b: {b_arr[0].tolist()}")


def basic_pattern_checks(name, a_first, b_first):
    """
    Conservative checks that visible pattern structure roughly matches the name.
    """
    checks = []

    if name == "max_carry_leading":
        checks.append(("a all 9s", all(x == 9 for x in a_first)))
        checks.append(("b all 0s", all(x == 0 for x in b_first)))

    elif name == "full_carry_chain":
        checks.append(("a all 9s", all(x == 9 for x in a_first)))
        checks.append(("b all 1s", all(x == 1 for x in b_first)))

    elif name == "single_carry_start":
        checks.append(("a starts with 5", len(a_first) > 0 and a_first[0] == 5))
        checks.append(("b starts with 5", len(b_first) > 0 and b_first[0] == 5))
        checks.append(("a tail zeros", all(x == 0 for x in a_first[1:])))
        checks.append(("b tail zeros", all(x == 0 for x in b_first[1:])))

    elif name == "alternating":
        a_expected = [9 if i % 2 == 0 else 0 for i in range(len(a_first))]
        b_expected = [1 if i % 2 == 0 else 0 for i in range(len(b_first))]
        checks.append(("a alternating 9/0", a_first == a_expected))
        checks.append(("b alternating 1/0", b_first == b_expected))

    elif name == "block_pattern":
        # Conservative block-pattern checks only
        checks.append(("contains 9 in a", 9 in a_first))
        checks.append(("contains 8 in b", 8 in b_first))
        checks.append(("contains 0 in both", 0 in a_first and 0 in b_first))

    return checks


# ============================================================================
# MAIN
# ============================================================================

def main():
    print_header("PHASE 5C: KILLER-TEST GROUND-TRUTH / PATTERN SEMANTICS VERIFICATION")
    print(f"Official target: {TARGET_FILE}")

    if not TARGET_FILE.exists():
        fail(f"Official target file not found: {TARGET_FILE}")

    module = load_target_module(TARGET_FILE)
    print("✓ Import successful")

    if not hasattr(module, "generate_test_patterns"):
        fail("Target module does not define generate_test_patterns()")

    generate_test_patterns = module.generate_test_patterns

    print_header("1) GENERATE PATTERNS")

    try:
        patterns = generate_test_patterns(length=20, num_samples=5)
        print("✓ Pattern generation succeeded")
    except Exception as e:
        fail(f"Pattern generation failed: {e}")

    if not isinstance(patterns, dict) or len(patterns) == 0:
        fail("Patterns object is empty or not dict-like")

    print(f"Generated pattern keys: {list(patterns.keys())}")

    print_header("2) ROW-BY-ROW PATTERN SEMANTICS CHECK")

    all_ok = True

    for name, value in patterns.items():
        if not (isinstance(value, tuple) and len(value) == 3):
            all_ok = False
            print(f"\n✗ Pattern {name}: invalid structure {type(value)}")
            continue

        a_arr, b_arr, desc = value

        if not isinstance(a_arr, np.ndarray) or not isinstance(b_arr, np.ndarray):
            all_ok = False
            print(f"\n✗ Pattern {name}: operands are not numpy arrays")
            continue

        if a_arr.shape != b_arr.shape:
            all_ok = False
            print(f"\n✗ Pattern {name}: shape mismatch a={a_arr.shape}, b={b_arr.shape}")
            continue

        describe_pattern_structure(name, a_arr, b_arr, desc)

        # Check first sample arithmetic
        a_first = a_arr[0].tolist()
        b_first = b_arr[0].tolist()
        expected_sum = reference_local_sum_sequence(a_first, b_first)

        print(f"Expected first-sample local sums: {expected_sum}")

        # Pattern-name structural checks
        checks = basic_pattern_checks(name, a_first, b_first)
        for label, ok in checks:
            marker = "✓" if ok else "✗"
            print(f"  {marker} {label}")
            if not ok:
                all_ok = False

        # Additional arithmetic sanity
        if not all(0 <= s <= 19 for s in expected_sum):
            all_ok = False
            print("  ✗ Local sums out of expected range [0..19]")
        else:
            print("  ✓ Local sums in expected range [0..19]")

    print_header("3) STEP 5C FINAL DECISION")

    if all_ok:
        print("✓ PASS")
        print()
        print("Finding:")
        print("  The generated killer-test patterns are structurally consistent with")
        print("  their descriptions and with independent carry-propagating arithmetic checks.")
        print()
        print("What this step established:")
        print("  - Pattern generation is not only executable but semantically coherent")
        print("  - The visible adversarial pattern names match the generated operand structure")
        print("  - Independent arithmetic sanity checks support the generated pattern content")
    else:
        print("✗ FAIL")
        print()
        print("Finding:")
        print("  One or more killer-test patterns did not match expected structural")
        print("  or arithmetic properties.")

    print()
    print("Qualification:")
    print("  This step verifies pattern semantics and arithmetic structure only.")
    print("  It does NOT verify model predictions or metric correctness.")

    print()
    print("Next step if accepted by user:")
    print("  Step 5D — metric verification / evaluation logic")

    print("\n" + "=" * 80)


if __name__ == "__main__":
    main()
